### ISSUE TITLE
Hidden Regions

### ISSUE THREAD

**Issue by khodgson2001** [webbukkit/Dynmap-WorldGuard#36]
I don't know where the problem is, but I have added i region i don't want to be visible, and when i reload/refresh the server to put the file in operation, it refreshes back to the default file. Whats wrong with it?
I am on 1.11

**Comment by seema84** [comment]
information is needed (server version/bild, dynmap version, dynmap worldguard version)

**Comment by khodgson2001** [comment]
I'm just gonna close this issue because it's 5 years old and the server isn't in use anymore. Sorry to waste your time!
