### ISSUE TITLE
Latest Snapshot Error

### ISSUE THREAD

**Issue by stijnb1234** [webbukkit/Dynmap-WorldGuard#51]
Hello there!

I'm using Spigot 1.13.2 and the correct versions of WorldEdit and WorldGuard that work with your plugin. Also I'm using the latest snapshot, but I get this error:
`[Dynmap-WorldGuard] Task #223433 for Dynmap-WorldGuard v1.1-SNAPSHOT generated an exception
05.03 20:48:24 [Server] INFO java.lang.NoSuchMethodError: com.sk89q.worldguard.WorldGuard.getProfileCache()Lcom/sk89q/squirrelid/cache/ProfileCache;
05.03 20:48:24 [Server] INFO at org.dynmap.worldguard.DynmapWorldGuardPlugin.formatInfoWindow(DynmapWorldGuardPlugin.java:116) ~[?:?]
05.03 20:48:24 [Server] INFO at org.dynmap.worldguard.DynmapWorldGuardPlugin.handleRegion(DynmapWorldGuardPlugin.java:284) ~[?:?]
05.03 20:48:24 [Server] INFO at org.dynmap.worldguard.DynmapWorldGuardPlugin.access$100(DynmapWorldGuardPlugin.java:45) ~[?:?]
05.03 20:48:24 [Server] INFO at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:350) ~[?:?]
05.03 20:48:24 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
05.03 20:48:24 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
05.03 20:48:24 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
05.03 20:48:24 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
05.03 20:48:24 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
05.03 20:48:24 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
05.03 20:48:24 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

Please fix this.

Thanks!
Stijn

**Comment by killertunes** [comment]
I'm getting the same error in the same situation. Thanks.

**Comment by PseudoKnight** [comment]
Apparently the latest commit fixes this, but there's no release yet.

**Comment by pavelGR83** [comment]
Latest commit  on 27 Jan. 

I hope the developer is aware of the problems. I have at all knocks plugin:

[Server thread/WARN]: [Dynmap-WorldGuard] Task #41 for Dynmap-WorldGuard v1.1 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.WorldGuard.getProfileCache()Lcom/sk89q/squirrelid/cache/ProfileCache;
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.formatInfoWindow(DynmapWorldGuardPlugin.java:116) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.handleRegion(DynmapWorldGuardPlugin.java:284) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.access$100(DynmapWorldGuardPlugin.java:45) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:350) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[craftbukkit.jar:git-Spigot-f09662d-7c395d4]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [craftbukkit.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [craftbukkit.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [craftbukkit.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [craftbukkit.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [craftbukkit.jar:git-Spigot-f09662d-7c395d4]
	at java.lang.Thread.run(Unknown Source) [?:?] 

WE 7.0.0 beta 05 
WG 7.0.0 beta 03

**Comment by mikeprimm** [comment]
Please try with latest dev build - https://dynmap.us/builds/Dynmap-WorldGuard/Dynmap-WorldGuard-1.2-SNAPSHOT.jar

**Comment by PseudoKnight** [comment]
So, we're getting the same error. WorldGuard is relocating the ProfileCache class path and this isn't reflected in the sk89q maven repo builds. I can only think of two solutions on this end: change the import to the new path and compile with an included jar that has the relocation, or use the maven shade plugin to relocate the ProfileCache class path in Dynmap-WorldGuard too. The latter is what I've done and it works great. Maybe someone has a better idea.

**Comment by RohugMC** [comment]
Hey @PseudoKnight , any possibility you could push your fix to a fork? :)

**Comment by PseudoKnight** [comment]
@RohugMC Done. I'm not sure if this is the best solution, but it's something. I guess what's important is that it produces a good compatible binary for those that want it right now.

https://github.com/PseudoKnight/Dynmap-WorldGuard/commit/eba7529b053508a7040fb0f892325d2b485f1284

**Comment by RohugMC** [comment]
Nice one, works for me. You should submit a PR :)

**Comment by mikeprimm** [comment]
Just grabbed this as a PR to myself :)   Thanks for the work - I'll give it a peek and include in next release!

**Comment by wizjany** [comment]
would really appreciate it if people just brought this up to me...

**Comment by wizjany** [comment]
as of https://github.com/EngineHub/WorldGuard/pull/415 this should no longer be an issue.
note that this is a source-breaking change for you since you explicitly import squirrelid: https://github.com/webbukkit/Dynmap-WorldGuard/blob/master/src/main/java/org/dynmap/worldguard/DynmapWorldGuardPlugin.java#L29
as of latest snapshots, you should now only need to depend on the `-bukkit` artifact and you should transitively get `-core` and `-libs:core` which will have squirrelid in the worldguard.util package.

your already-relocated binaries should work fine, since the runtime binaries always had profile stuff in the worldguard.util package.

**Comment by seema84** [comment]
@mikeprimm can the issu be closed?
