### ISSUE TITLE
Dynmap-Worldguard not shutting down correctly

### ISSUE THREAD

**Issue by Relaxing9** [webbukkit/Dynmap-WorldGuard#64]
I am running Dynmap-WorldGuard version: 1.2
I am running Paper-Spigot Version: git-Paper-506 (MC: 1.16.5)

And my log is reporting that this plugin is not properly shutting down on server shutdown
[Server Log](https://paste.gg/p/anonymous/9bb5a95e9e9c445787ca93aaddf5a691)
`[03:46:42] [Server thread/ERROR]: Nag author: 'mikeprimm' of 'Dynmap-WorldGuard' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

**Comment by seema84** [comment]
try the latest snapshot
http://mikeprimm.com/dynmap/builds/Dynmap-WorldGuard//

**Comment by Relaxing9** [comment]
> try the latest snapshot
> http://mikeprimm.com/dynmap/builds/Dynmap-WorldGuard//

There is no latest snapshot, the last snapshot was just a transfer to a development build. Last official build was 12/15/2019 and this is the same with the latest development build, so I highly doubt that a developer build would solve this issue.

**Comment by seema84** [comment]
Dynmap-WorldGuard-1.2.jar has a different size than Dynmap-WorldGuard-1.3-SNAPSHOT.jar

**Comment by seema84** [comment]
that is correct
in the last snapshot there is only this commit https://github.com/webbukkit/Dynmap-WorldGuard/commit/c37a2fa101262d88ff1fafac8ab2a43ca68d7e85

**Comment by Relaxing9** [comment]
Closing this since c4980b8159edfd6628073dc66a5d236bcb39bb67 upgraded the plugin from Legacy (to support latest server version) & I believe this should fix it not shutting down correctly.
